name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the website
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        name: build-artifact
        path: ./build

    - name: Deploy to GitHub Pages
      if: success()
      uses: actions/deploy-pages@v1
      with:
        folder: ./build